add zulu jdk plugin
version-fox/version-fox-plugins pull request #11
Opened 2024-02-04 08:08 UTC by yimiaoxiehou

support install jdk via [zulu ](https://www.azul.com/downloads/#zulu)

just test passwd in ubuntu22(amd64). have not other test env.

test output:
```
root@yimiao-ltp:/home/yimiao/workspace/version-fox-plugins/java# vfox  add  --source ./azul-jdk.lua
Loading plugin from ./azul-jdk.lua...
Checking plugin...
Plugin info:
Name    -> java
Author  -> yimiaoxiehou
Version -> 0.0.1
Desc    -> Azul JDK, also known as Zulu
Path    -> /root/.version-fox/plugin/java.lua
Add java plugin successfully! 
Please use `vfox install java@<version>` to install the version you need.
root@yimiao-ltp:/home/yimiao/workspace/version-fox-plugins/java# vfox ls
All installed sdk versions
├──java
├─┬nodejs
│ └──v21.6.1
└─┬golang
  └──v1.21.6

root@yimiao-ltp:/home/yimiao/workspace/version-fox-plugins/java# vfox search
sdk name is required
root@yimiao-ltp:/home/yimiao/workspace/version-fox-plugins/java# vfox search java
Please select a version of java [type to search]: 
   v21 (LTS)
   v20
   v19
   v18
   v17 (LTS)
   v13
->  v11 (LTS)
   v8 (LTS)
   v7 (LTS)
   v6 (LTS)
Press ↑/↓ to select and press ←/→ to page, and press Enter to confirm
Installing java@11...
Downloading... 100% [==========================================================================================================================================] (2.3 MB/s)           
Verifying checksum bd0f4e71328854d3dc21c98c88cccaabcc64353e2d6bcd6da89198a303d246b7...
Unpacking /root/.version-fox/cache/java/zulu11.70.15-ca-jdk11.0.22-linux_x64.zip...
Install java@11 success! 
Please use vfox use java@11 to use it.
root@yimiao-ltp:/home/yimiao/workspace/version-fox-plugins/java# vfox use java@11
Warning: The current shell lacks hook support or configuration. It has switched to global scope automatically.
Now using java@11.
root@yimiao-ltp:/home/yimiao/workspace/version-fox-plugins/java# java -version
openjdk version "11.0.22" 2024-01-16 LTS
OpenJDK Runtime Environment Zulu11.70+15-CA (build 11.0.22+7-LTS)
OpenJDK 64-Bit Server VM Zulu11.70+15-CA (build 11.0.22+7-LTS, mixed mode)
```

2024-02-04 10:20 UTC, aooohan commented
Great!   Although I haven't reviewed it yet, from the log you posted, I found a problem. ;)
> ```
> root@yimiao-ltp:/home/yimiao/workspace/version-fox-plugins/java# vfox use java@11
> Warning: The current shell lacks hook support or configuration. It has switched to global scope automatically.
> ```

If your shell prompt `Warning:The current shell lacks hook support or configuration. It has switched to global scope automatically` that means you do not hook `vfox` into your shell, please hook it manually first.

It works, but it's not a good experience.

2024-02-05 03:01 UTC, aooohan commented on java/azul-jdk.lua
> +local html = require("html")
This html module is not used, it needs to be removed.

2024-02-05 14:36 UTC, aooohan requested changes

2024-02-05 14:36 UTC, aooohan commented on java/azul-jdk.lua
> +local html = require("html")
```suggestion
```

2024-02-05 14:37 UTC, merged

2024-02-05 14:48 UTC, aooohan commented
Thanks for the PR. ;)

2024-02-18 02:06 UTC, yimiaoxiehou commented on java/azul-jdk.lua
> +local html = require("html")
春节快了，放假了没看邮件  ^-^