Support PHP Plugin
version-fox/version-fox-plugins pull request #23
Opened 2024-03-01 13:44 UTC by Chance-fyi

version-fox/vfox#55

2024-03-02 06:18 UTC, aooohan requested changes
Thanks for your contribution.

I tested it briefly, but it didn't work on `macOS`.
```bash
configure: error: in `/Users/lihan/.version-fox/cache/php/v-8.3.0/tmp-8.3.0':
configure: error: The pkg-config script could not be found or is too old.  Make sure it
is in your PATH or set the PKG_CONFIG environment variable to the full
path to pkg-config.

Alternatively, you may set the environment variables LIBXML_CFLAGS
and LIBXML_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

To get pkg-config, see <http://pkg-config.freedesktop.org/>.
See `config.log' for more details
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target `install'.  Stop.
/bin/sh: line 0: cd: /Users/lihan/.version-fox/cache/php/v-8.3.0/php-8.3.0/bin: No such file or directory
/bin/sh: line 0: cd: /Users/lihan/.version-fox/cache/php/v-8.3.0/php-8.3.0/bin: No such file or directory
Install php@8.3.0 success! 
Please use vfox use php@8.3.0 to use it.
```

2024-03-02 06:18 UTC, aooohan commented on php/php.lua
> +    version = "0.0.1",
Please add simple description for this plugin.

2024-03-02 06:18 UTC, aooohan commented on php/php.lua
> +    os.execute("mv " .. path .. " " .. install_path)
There should handle the failure of the command to execute, otherwise `vfox` will treat the installation as successful, and it will actually fail.

2024-03-02 11:14 UTC, Chance-fyi commented
> I tested it briefly, but it didn't work on `macOS`.

Sorry, I don't have a `macOS` environment. Can you help?

2024-03-02 11:55 UTC, aooohan commented
> > I tested it briefly, but it didn't work on `macOS`.
> 
> Sorry, I don't have a `macOS` environment. Can you help?

Of course.

2024-03-06 06:38 UTC, aooohan commented
@Chance-fyi Have you tested this plugin on Linux?

2024-03-06 06:47 UTC, Chance-fyi commented
> @Chance-fyi Have you tested this plugin on Linux?

Yes, I tested it. Is there a problem?

2024-03-06 06:55 UTC, aooohan commented
> > @Chance-fyi Have you tested this plugin on Linux?
> 
> Yes, I tested it. Is there a problem?

Because on macOS, there are some missing dependencies.  Such as:

```shell
The pkg-config script could not be found or is too old.  Make sure it
is in your PATH or set the PKG_CONFIG environment variable to the full
path to pkg-config.
```

We may need to ask macOS users to install `Homebrew` and then install some dependencies via it. 

OR 

We directly utilize the build tools that are readily available in the `php` ecosystem, like https://github.com/php-build/php-build. Just like how I implement python's build on `unix-like`.

2024-03-06 07:17 UTC, Chance-fyi commented
I see asdf is installing some dependencies via `Homebrew`.

https://github.com/asdf-community/asdf-php/blob/master/bin/install

Or just use `Homebrew` to install PHP.

```bash
brew install php
```

2024-03-06 07:57 UTC, aooohan commented
> I see asdf is installing some dependencies via `Homebrew`.
> 
> https://github.com/asdf-community/asdf-php/blob/master/bin/install
> 
> Or just use `Homebrew` to install PHP.
> 
> ```shell
> brew install php
> ```

First, excluding the use of Homebrew direct installation as we need to customize storage path, I think we directly follow the asdf plugin to implement it.

2024-04-01 08:00 UTC, aooohan commented
@Chance-fyi Hi, Can use reimplement this by new template? Refer:
https://vfox.lhan.me/zh-hans/plugins/create/howto.html

2024-04-01 08:37 UTC, Chance-fyi commented
> @Chance-fyi Hi, Can use reimplement this by new template? Refer: https://vfox.lhan.me/zh-hans/plugins/create/howto.html

Okay, I'll finish it.

2024-04-11 01:58 UTC, closed without merging